blog/urls.py
from django.urls import path
from .views import RequestListView, RequestDetailView, RequestUpdateView, RequestDeleteView
from . import views # Le "." désigne le fichier courant


# Liste de chemins qui a été importée
urlpatterns = [
    path('', RequestListView.as_view(), name='blog-home'), # localhost:8000/blog/
    path('request/<int:pk>/', RequestDetailView.as_view(), name='request-detail'), #affiche les détails d'une Request
    #pk = primary key --> exemple : Request/1 = Request avec l'id 1, le int: sert à dire que le pk est de type int afin d'éviter que qlq mette un string par exemple
    path('request/<int:pk>/update/', RequestUpdateView.as_view(), name='request-update'), #modifier une Request
    path('request/<int:pk>/delete/', RequestDeleteView.as_view(), name='request-delete'), #supprimer une Request
    path('request/new/', views.create_request, name='request-create'), #creation d'une requête
    path('about/', views.about, name='blog-about'), # localhost:8000/about/
    path('admin_panel/', views.admin_panel, name='admin-panel'),
    path('admin_panel/create_user/', views.create_account, name='create-user'),
    path('update_user/<int:pk>/', views.update_account, name='update-user'),
    #path('user/<int:pk>/', UserDetailView.as_view(), name='detail-user'),


]

project_team5/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

# Liste de chemins qui a été importée
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('', include('blog.urls')), #localhost:8000/blog/
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from PIL import Image

PRIORITY_CHOICES = (
    ('1', 'Highest'),
    ('2', 'High'),
    ('3', 'Medium'),
    ('4', 'Low'),
    ('5', 'Lowest'),
)

STATUS_CHOICES = (
    ('1', 'Pending'),
    ('2', 'Proposed'),
    ('3', 'Interview'),
    ('4', 'Results won'),
    ('5', 'Results lost'),
    ('6', 'No resource'),
)

LEVEL_CHOICES = (
    ('1', 'Junior'),
    ('2', 'Senior'),
)

class Request(models.Model): #creation d'une requete
    title = models.CharField(max_length=100)
    reference_number = models.CharField(max_length=100)
    start_date = models.CharField(max_length=100)
    deadline = models.DateField()
    budget = models.DecimalField(default=0, max_digits=15, decimal_places=2)
    priority = models.CharField(default='3', max_length=10, choices=PRIORITY_CHOICES)
    faction = models.CharField(max_length=100)
    consultant = models.CharField(max_length=100) #consultant assigné à la mission
    main_skills = models.CharField(max_length=100)  #skills du consultant (exemple : Java)
    consultant_level = models.CharField(default='1', max_length=10, choices=LEVEL_CHOICES)
    status = models.CharField(default='1', max_length=10, choices=STATUS_CHOICES)
    attachment = models.FileField(upload_to='public', null=True)
    date_requested = models.DateTimeField(default=timezone.now)
    #author = models.ForeignKey(User, on_delete=models.CASCADE) #reférence à une autre classe (clé étrangère)
    #on_delete=models.CASCADE --> signifie que lors de la suppression d'un User, tous ses Requests seront supprimés aussi

    def save(self, *args, **kwargs):  # method that runs after our model is saved --> méthode qui existe déjà mais on va la réécrire afin d'ajouter des fonctionnalités
        super(Request, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('request-detail', kwargs={'pk' : self.pk}) #redirige vers la page "Request-detail" et enregistre la clé primaire du nouveau Request

blog/forms.py
from django import forms
from .models import Request
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


RIGHT_CHOICES =(
    (False, "No rights (read only)"),
    (True, "Administrator rights"),
)


class UserCreationForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(label="First name")
    last_name = forms.CharField(label="Last name")
    is_staff = forms.ChoiceField(label="User rights",choices=RIGHT_CHOICES)

    class Meta :
        model = User
        fields = ['username', 'email', 'first_name', 'last_name','password1', 'password2', 'is_staff']


class UserCreationUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    first_name = forms.CharField(label="First name")
    last_name = forms.CharField(label="Last name")
    is_staff = forms.ChoiceField(label="User rights",choices=RIGHT_CHOICES)

    class Meta :
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'is_staff']



class RequestCreationForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ['title', 'reference_number', 'start_date', 'deadline', 'priority', 'budget', 'status', 'faction',
                  'consultant', 'main_skills', 'consultant_level', 'attachment']

    def __init__(self, *args, **kwargs):
        super(RequestCreationForm, self).__init__(*args, **kwargs)
        self.fields['attachment'].required = False

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Request
from django.contrib import messages
from django.contrib.auth import get_user_model
from .forms import UserCreationForm,RequestCreationForm, UserCreationUpdateForm


# Fichier qui va contenir toutes les vues de notre application

# la fonction home prend en paramètre une requête http --> return une réponse http contenant un code html
@login_required
def home(request):
    context = {
        'requests' : Request.objects.all()
    }
    return render(request, 'blog/home.html', context) #requête en paramètre, nomDuRepertoire/nomDuTemplate

@login_required
def create_request(request):
    if request.method == 'POST':
        form = RequestCreationForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, f'The request has been created successfully !')
            return redirect('blog-home')
    else:
        form = RequestCreationForm()

    return render(request, 'blog/request_form.html', {'form':form})

@login_required
def admin_panel(request):
    context = {
        'users' : User.objects.all()
    }

    return render(request, 'blog/admin_panel.html', context)

@login_required
def create_account(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            #username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('admin-panel') #une fois le compte créer, redirection vers la page de login
    else:
        form = UserCreationForm()

    return render(request, 'blog/create_user.html', {'form':form})


#méthode concernant la modification des utilisateurs
@login_required
def update_account(request, pk):
    user = User.objects.get(id=pk)
    u_form = UserCreationUpdateForm(instance=user)

    if request.method == 'POST':
        form = UserCreationUpdateForm(request.POST,instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, f'The account has been modified !')
            return redirect('admin-panel') #redirection vers la page d'admin


    context = {
        'u_form': u_form,
    }

    return render(request,'blog/user_account_update.html', context)



class RequestListView(LoginRequiredMixin, ListView): #affichage de tous les requests (home.html)
    model = Request
    template_name = 'blog/home.html'#<app>/<model>_<viewtype>.html
    context_object_name = 'requests'
    ordering = ['-date_requested'] #permet d'afficher les requests du plus récent au plus ancien (grâce au '-' devant date_Requested)
    #paginate_by = 5 #nombre de requests qui vont être affichés sur une page

class RequestDetailView(LoginRequiredMixin, DetailView): #quand on clique sur un Request, le Request va être afficher de manière bcp + détaillée
    model = Request

class RequestUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):  # création d'un Request
    model = Request
    fields = ['title','reference_number','start_date','deadline','priority' ,'budget', 'status','faction', 'consultant', 'main_skills', 'consultant_level', 'attachment']

    def form_valid(self, form):
        form.instance.author = self.request.user  # auteur de la requête = l'utilisateur actuellement connecté
        return super().form_valid(form)

    def test_func(self):
        Request = self.get_object() #enregistre le Request que l'on veut actuellement modifier
        if self.request.user.is_staff: #si l'utilsateur connecté correspond à l'auteur du Request alors il peut modifier le Request (return True)
            return True
        return False

class RequestDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView): #quand on clique sur un Request, le Request va être afficher de manière bcp + détaillée
    model = Request
    success_url = '/'

    def test_func(self):
        Request = self.get_object() #enregistre le Request que l'on veut actuellement supprimer
        if self.request.user.is_staff: #si l'utilsateur connecté correspond à l'auteur du Request alors il peut supprimer le Request (return True)
            return True
        return False

def about(request):
    return render(request, 'blog/about.html', {'title' : 'My About Page'})

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}

    <h1>My About Page</h1>

{% endblock content %}

blog/templates/blog/admin_panel.html
{% extends "blog/base.html" %}

{% block content %}

{% if user.is_staff %}

<div class="container p-30">
    <div class="row">
        <div class="col-md-12 main-datatable">
            <div class="card_body">
                <div class="row d-flex">
                    <div class="col-sm-4 createSegment"> 
                     <a class="btn dim_button create_new" href="{% url 'create-user' %}"> <span class="glyphicon glyphicon-plus"></span> Create A New User</a>
                    </div>
                    <div class="col-sm-8 add_flex">
                        <div class="form-group searchInput">
                            <label for="email">Search:</label>
                            <input type="search" class="form-control" id="filterbox2" placeholder=" ">
                        </div>
                    </div> 
                </div>
                <div class="overflow-x">
                    <table style="width:100%;" id="filtertable2" class="table cust-datatable dataTable no-footer">
                        <thead>
                            <tr>
                                <th>Username</th>
                                <th>E-mail</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Rights</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                                {% for user in users %}
                            <tr>

                                <td>{{ user.username }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                {% if user.is_staff %}
                                    <td> Administrator </td>
                                {% else %}
                                    <td> Read-only </td>
                                {% endif %}
                                <td>
                                    <div class="btn-group">
                                        <a class="dropdown-toggle dropdown_icon" data-toggle="dropdown">
                                            <i class="fa fa-ellipsis-h"></i>
                                        </a>
                                        <ul class="dropdown-menu dropdown_more">
                                            <li>
                                                <a href="#" target="_black">
                                                    <i class="fa fa-trash"></i> Delete
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'update-user' user.id %}" target="_black">
                                                    <i class="fa fa-pencil fa-fw"></i>Modify rights</a>
                                                </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>

                            {% endfor %}                              
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div> 

{% else %}

    <h2>You don't have access to this page</h2>

{% endif %}

{% endblock content %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.14/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">

    
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,800&display=swap" rel="stylesheet">

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />

    {% if title %}
        <title>Django - {{ title }}</title>
    {% else %}
        <title>Django Default</title>
    {% endif %}

</head>
<body>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <!-- bouton 3 barres qd site en petit -->
            <button aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
                    data-target="#navbarToggle" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse" id="navbarToggle">
                <!-- Navbar partie de gauche -->
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog-home' %}"><i class="fa fa-home"></i> Home</a>
                    <a class="nav-item nav-link" href="{% url 'blog-about' %}"><i class="fa fa-info-circle"></i> About</a>
                </div>

                <!-- <div class="navbar-nav mx-auto">
                     <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search a request" aria-label="Search">
                        <button class="btn btn-dark ml-2" type="submit">Search</button>
                     </form>
                </div> -->

                <!-- Navbar partie droite -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %} <!-- si l'utilisateur est connecté -->
                        {% if user.is_staff %}
                        <a class="nav-item nav-link" href="{% url 'request-create' %}"><i class="fa fa-plus"></i> New request</a>
                        <a class="nav-item nav-link" href="{% url 'admin-panel' %}"><i class="fa fa-cog"></i> Admin Panel</a>
                        {% endif %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}"><i class="fa fa-user"></i> Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
                    {% else %} <!-- si l'utilisateur n'est pas connecté -->
                        <a class="nav-item nav-link" href="{% url 'login' %}"><i class="fa fa-sign-in"></i> Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-12">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
      {% block content %} {% endblock %}
    </div>
      <!-- Sidebar -->
  <!--
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
   -->
  </div>
</main>

<script src="https://use.fontawesome.com/96efc4366e.js"></script>
<script src="https://use.fontawesome.com/a969cfc98a.js"></script>
<script src="https://use.fontawesome.com/355214ab4a.js"></script>
<script src="https://use.fontawesome.com/cd089ff891.js"></script>
<script src="https://use.fontawesome.com/3820ab10a5.js"></script>
<script src="https://use.fontawesome.com/d00235ec58.js"></script>



<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script crossorigin="anonymous"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>






<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/responsive/2.3.0/js/responsive.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.14/js/jquery.dataTables.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.14/js/jquery.dataTables.min.js"></script>
<script src="{% static 'blog/app.js' %}"></script>

<script>
    $(function(){
        $("#id_start_date").datepicker();
        $("#id_deadline").datepicker();
    });
</script>
</body>
</html>

blog/templates/blog/create_user.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

{% if user.is_staff %}

<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> New User </legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Create User</button>
        </div>
    </form>
</div>

{% else %}
    <h2>You don't have access to this page</h2>
{% endif %}

{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% block content %}

<div class="container p-30">
    <div class="row">
        <div class="col-md-12 main-datatable">
            <div class="card_body">
                <div class="row d-flex">
                    <div class="col-sm-4 createSegment"> 
                     <a class="btn dim_button create_new" href="{% url 'request-create' %}"> <span class="glyphicon glyphicon-plus"></span> Create A New Request</a>
                    </div>
                    <div class="col-sm-8 add_flex">
                        <div class="form-group searchInput">
                            <label for="email">Search:</label>
                            <input type="search" class="form-control" id="filterbox" placeholder=" ">
                        </div>
                    </div> 
                </div>
                <div class="overflow-x">
                    <table style="width:100%;" id="filtertable" class="table cust-datatable dataTable no-footer">
                        <thead>
                            <tr>
                                <th >Title</th>
                                <th >Reference</th>
                                <th >Start date</th>
                                <th >Deadline</th>
                                <!-- si l'utilisateur est un administrateur : affichage du Budget -->
                                {% if user.is_staff %}
                                <th >Budget</th>
                                {% endif %}
                                <th >Priority</th>
                                <th >Faction</th>
                                <th >Consultant</th>
                                <th >Main skills</th>
                                <th>Consultant level</th>
                                <th>Status</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>

                                {% for request in requests %}
                            <tr>

                                <td>{{request.title}}</td>
                                <td>{{request.reference_number}}</td>
                                <td>{{request.start_date}}</td>
                                <td>{{request.deadline}}</td>
                                {% if user.is_staff %}
                                <td>{{request.budget}}</td>
                                {% endif %}
                                <td>{{request.get_priority_display}}</td>
                                <td>{{request.faction}}</td>
                                <td>{{request.consultant}}</td>
                                <td>{{request.main_skills}}</td>
                                <td>{{request.get_consultant_level_display}}</td>
                                {% if request.status == "1" %}
                                <td><span class="mode mode_done">{{request.get_status_display}}</span></td>
                                {% elif request.status == "2" %}
                                <td><span class="mode mode_process">{{request.get_status_display}}</span></td>
                                {% else %}
                                <td><span class="mode mode_off">{{request.get_status_display}}</span></td>


                                {% endif %}

                                <td>
                                    <div class="btn-group">
                                        <a class="dropdown-toggle dropdown_icon" data-toggle="dropdown">
                                            <i class="fa fa-ellipsis-h"></i>
                                        </a>
                                        <ul class="dropdown-menu dropdown_more">
                                            <li>
                                                <a href="{% url 'request-delete' request.id %}" target="_black">
                                                    <i class="fa fa-trash"></i> Delete
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'request-update' request.id %}" target="_black">
                                                    <i class="fa fa-pencil fa-fw"></i>Update</a>
                                                </li>
                                            <li>
                                                <a href="{% url 'request-detail' request.id %}" target="_black">
                                                    <i class="fa fa-list"></i>Detail</a>
                                                </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>

                            {% endfor %}                              
                                
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div> 



{% endblock content %}

blog/templates/blog/request_detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <article class="media content-section">

<div class="container p-30">
    <div class="row">
        <div class="col-md-12 main-datatable">
            <div class="card_body">

                <div class="overflow-x">
                    <table style="width:100%;" id="filtertable" class="table cust-datatable dataTable no-footer">
                        <thead>
                            <tr>
                                <th >Title</th>
                                <th >Reference</th>
                                <th >Start date</th>
                                <th >Deadline</th>
                                <!-- si l'utilisateur est un administrateur : affichage du Budget -->
                                {% if user.is_staff %}
                                <th >Budget</th>
                                {% endif %}
                                <th >Priority</th>
                                <th >Faction</th>
                                <th >Consultant</th>
                                <th >Main skills</th>
                                <th>Consultant level</th>
                                <th>Status</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>


                            <tr>
                                <td>{{object.title}}</td>
                                <td>{{object.reference_number}}</td>
                                <td>{{object.start_date}}</td>
                                <td>{{object.deadline}}</td>
                                {% if user.is_staff %}
                                <td>{{object.budget}}</td>
                                {% endif %}
                                <td>{{object.get_priority_display}}</td>
                                <td>{{object.faction}}</td>
                                <td>{{object.consultant}}</td>
                                <td>{{object.main_skills}}</td>
                                <td>{{object.get_consultant_level_display}}</td>
                                {% if object.status == "1" %}
                                <td><span class="mode mode_done">{{object.get_status_display}}</span></td>
                                {% elif object.status == "2" %}
                                <td><span class="mode mode_process">{{object.get_status_display}}</span></td>
                                {% else %}
                                <td><span class="mode mode_off">{{object.get_status_display}}</span></td>

                                {% endif %}

                                <td>
                                    <div class="btn-group">
                                        <a class="dropdown-toggle dropdown_icon" data-toggle="dropdown">
                                            <i class="fa fa-ellipsis-h"></i>
                                        </a>
                                        <ul class="dropdown-menu dropdown_more">
                                            <li>
                                                <a href="{% url 'request-delete' object.id %}" target="_black">
                                                    <i class="fa fa-trash"></i> Delete
                                                </a>
                                            </li>
                                            <li>
                                                <a href="{% url 'request-update' request.id %}" target="_black">
                                                    <i class="fa fa-list"></i>Update</a>
                                                </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                     </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
    </article>
{% endblock content %}